#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} docker image build \
    --build-arg CONTAINERD_VERSION=${CONTAINERD_VERSION} \
    --build-arg ARCH=${GOARCH} \
    --build-arg PROTOC_VERSION=${PROTOC_VERSION} \
    --tag ${REPO}/hardened-containerd:${CONTAINERD_VERSION} \
    --tag ${REPO}/hardened-containerd:${CONTAINERD_VERSION}-${GOARCH} \
    --target containerd \
.

DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} docker image build \
    --build-arg RUNC_VERSION=${RUNC_VERSION} \
    --build-arg ARCH=${GOARCH} \
    --tag ${REPO}/hardened-runc:${RUNC_VERSION} \
    --tag ${REPO}/hardened-runc:${RUNC_VERSION}-${GOARCH} \
    --target runc \
.

DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} docker image build \
    --build-arg CRICTL_VERSION=${CRICTL_VERSION} \
    --build-arg ARCH=${GOARCH} \
    --tag ${REPO}/hardened-crictl:${CRICTL_VERSION} \
    --tag ${REPO}/hardened-crictl:${CRICTL_VERSION}-${GOARCH} \
    --target crictl \
.

DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} docker image build \
    --build-arg TAG=${VERSION} \
    --build-arg ARCH=${GOARCH} \
    --build-arg KUBERNETES_VERSION=${KUBERNETES_VERSION} \
    --build-arg MAJOR=${VERSION_MAJOR} \
    --build-arg MINOR=${VERSION_MINOR} \
    --build-arg CACHEBUST="$(date +%s%N)" \
    --build-arg RUNC_VERSION=${RUNC_VERSION} \
    --build-arg CRICTL_VERSION=${CRICTL_VERSION} \
    --build-arg CONTAINERD_VERSION=${CONTAINERD_VERSION} \
    --build-arg K3S_VERSION=${K3S_VERSION} \
    --tag ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION} \
    --tag ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-${GOARCH} \
    --target runtime \
.

mkdir -p build/images
docker image save \
    --output build/images/${PROG}-runtime.tar \
    ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION} \
    ${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}-${GOARCH}
