#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh
mkdir -p build/images
./scripts/build-binary
[ "${GOARCH}" != "arm64" ] && ./scripts/build-windows-binary
./scripts/build-images
[ "${GOARCH}" != "arm64" ] && ./scripts/build-windows-images
./scripts/package-bundle
[ "${GOARCH}" != "arm64" ] && ./scripts/package-windows-bundle
./scripts/dev-runtime-image
./scripts/dev-rpm
./scripts/build-image-test
