#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh
mkdir -p build/images
./scripts/build-binary
if [ "${ARCH}" = "amd64" ]; then ./scripts/build-windows-binary; fi
./scripts/build-images
./scripts/package-bundle
if [ "${ARCH}" = "amd64" ]; then ./scripts/package-windows-bundle; fi
./scripts/dev-runtime-image
./scripts/build-image-test
