#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

./scripts/build-image-runtime

awk '{print $1}' << EOF > build/images-core.txt
    ${REGISTRY}/${REPO}/${PROG}-runtime:${DOCKERIZED_VERSION}
EOF

xargs -n1 -t docker image pull --quiet << EOF >> build/images-core.txt
    ${REGISTRY}/${REPO}/hardened-kubernetes:${KUBERNETES_IMAGE_TAG}
    ${REGISTRY}/${REPO}/hardened-coredns:v1.10.1-build20230503
    ${REGISTRY}/${REPO}/hardened-cluster-autoscaler:v1.8.6-build20230503
    ${REGISTRY}/${REPO}/hardened-dns-node-cache:1.22.20-build20230503
    ${REGISTRY}/${REPO}/hardened-etcd:${ETCD_VERSION}-build20230502
    ${REGISTRY}/${REPO}/hardened-k8s-metrics-server:v0.6.2-build20230503
    ${REGISTRY}/rancher/klipper-helm:v0.7.6-build20230223
    ${REGISTRY}/rancher/klipper-lb:v0.4.3
    ${REGISTRY}/${REPO}/pause:${PAUSE_VERSION}
    ${REGISTRY}/rancher/mirrored-ingress-nginx-kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
    ${REGISTRY}/${REPO}/nginx-ingress-controller:nginx-1.6.4-hardened4-multiarch
    ${REGISTRY}/${REPO}/rke2-cloud-provider:${CCM_VERSION}
    ${REGISTRY}/rancher/mirrored-sig-storage-snapshot-controller:v6.2.1
    ${REGISTRY}/rancher/mirrored-sig-storage-snapshot-validation-webhook:v6.2.1
EOF

xargs -n1 -t docker image pull --quiet << EOF > build/images-canal.txt
    ${REGISTRY}/${REPO}/hardened-calico:v3.25.0-build20230503
    ${REGISTRY}/${REPO}/hardened-flannel:v0.21.3-build20230503
EOF

if [ "${GOARCH}" != "s390x" ]; then
xargs -n1 -t docker image pull --quiet << EOF > build/images-cilium.txt
    ${REGISTRY}/rancher/mirrored-cilium-certgen:v0.1.8
    ${REGISTRY}/rancher/mirrored-cilium-cilium:v1.13.0
    ${REGISTRY}/rancher/mirrored-cilium-clustermesh-apiserver:v1.13.0
    ${REGISTRY}/rancher/mirrored-cilium-hubble-relay:v1.13.0
    ${REGISTRY}/rancher/mirrored-cilium-hubble-ui:v0.10.0
    ${REGISTRY}/rancher/mirrored-cilium-hubble-ui-backend:v0.10.0
    ${REGISTRY}/rancher/mirrored-cilium-operator-aws:v1.13.0
    ${REGISTRY}/rancher/mirrored-cilium-operator-azure:v1.13.0
    ${REGISTRY}/rancher/mirrored-cilium-operator-generic:v1.13.0
    ${REGISTRY}/${REPO}/hardened-cni-plugins:v1.0.1-build20230503
EOF
if [ "${GOARCH}" != "arm64" ]; then
xargs -n1 -t docker image pull --quiet << EOF >> build/images-cilium.txt
    ${REGISTRY}/rancher/mirrored-cilium-cilium-etcd-operator:v2.0.7
EOF
fi

xargs -n1 -t docker image pull --quiet << EOF > build/images-calico.txt
    ${REGISTRY}/rancher/mirrored-calico-operator:v1.29.0
    ${REGISTRY}/rancher/mirrored-calico-ctl:v3.25.0
    ${REGISTRY}/rancher/mirrored-calico-kube-controllers:v3.25.0
    ${REGISTRY}/rancher/mirrored-calico-typha:v3.25.0
    ${REGISTRY}/rancher/mirrored-calico-node:v3.25.0
    ${REGISTRY}/rancher/mirrored-calico-pod2daemon-flexvol:v3.25.0
    ${REGISTRY}/rancher/mirrored-calico-cni:v3.25.0
    ${REGISTRY}/rancher/mirrored-calico-apiserver:v3.25.0
EOF

if [ "${GOARCH}" != "arm64" ]; then
xargs -n1 -t docker image pull --quiet << EOF > build/images-vsphere.txt
    ${REGISTRY}/rancher/mirrored-cilium-cilium-etcd-operator:v2.0.7
    ${REGISTRY}/rancher/mirrored-cloud-provider-vsphere-cpi-release-manager:v1.25.0
    ${REGISTRY}/rancher/mirrored-cloud-provider-vsphere-csi-release-driver:v2.7.0
    ${REGISTRY}/rancher/mirrored-cloud-provider-vsphere-csi-release-syncer:v2.7.0
    ${REGISTRY}/rancher/mirrored-sig-storage-csi-node-driver-registrar:v2.5.1
    ${REGISTRY}/rancher/mirrored-sig-storage-csi-resizer:v1.4.0
    ${REGISTRY}/rancher/mirrored-sig-storage-livenessprobe:v2.7.0
    ${REGISTRY}/rancher/mirrored-sig-storage-csi-attacher:v3.4.0
    ${REGISTRY}/rancher/mirrored-sig-storage-csi-provisioner:v3.2.1
EOF
fi

xargs -n1 -t docker image pull --quiet << EOF > build/images-multus.txt
    ${REGISTRY}/${REPO}/hardened-multus-cni:v3.9.3-build20230504
    ${REGISTRY}/${REPO}/hardened-cni-plugins:v1.0.1-build20230503
    ${REGISTRY}/${REPO}/hardened-sriov-network-operator:v1.2.0-build20230504
    ${REGISTRY}/${REPO}/hardened-sriov-network-config-daemon:v1.2.0-build20230504
    ${REGISTRY}/${REPO}/hardened-sriov-network-device-plugin:v3.5.1-build20230504
    ${REGISTRY}/${REPO}/hardened-sriov-cni:v2.6.3-build20230504
    ${REGISTRY}/${REPO}/hardened-ib-sriov-cni:v1.0.2-build20230504
    ${REGISTRY}/${REPO}/hardened-sriov-network-resources-injector:v1.5-build20230504
    ${REGISTRY}/${REPO}/hardened-sriov-network-webhook:v1.2.0-build20230504
    ${REGISTRY}/${REPO}/hardened-whereabouts:v0.6.1-build20230504
EOF

xargs -n1 -t docker image pull --quiet << EOF > build/images-harvester.txt
    ${REGISTRY}/rancher/harvester-cloud-provider:v0.1.5
    ${REGISTRY}/rancher/harvester-csi-driver:v0.1.5
    ${REGISTRY}/rancher/longhornio-csi-node-driver-registrar:v2.3.0
    ${REGISTRY}/rancher/longhornio-csi-resizer:v1.2.0
    ${REGISTRY}/rancher/longhornio-csi-provisioner:v2.1.2
    ${REGISTRY}/rancher/longhornio-csi-attacher:v3.2.1
EOF
fi
# Continue to provide a legacy airgap archive set with the default CNI images
cat build/images-core.txt build/images-canal.txt > build/images.txt
