#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} docker image build \
    --build-arg TAG=${VERSION} \
    --build-arg BASE_VERSION=${BASE_VERSION} \
    --build-arg TARGETARCH=${ARCH} \
    --build-arg KUBERNETES_VERSION=${KUBERNETES_VERSION} \
    --build-arg KUBERNETES_IMAGE_TAG=${KUBERNETES_IMAGE_TAG}-${IMAGE_BUILD_VERSION} \
    --build-arg RUNC_VERSION=${RUNC_VERSION}-${IMAGE_BUILD_VERSION} \
    --build-arg CRICTL_VERSION=${CRICTL_VERSION}-${IMAGE_BUILD_VERSION} \
    --build-arg CONTAINERD_VERSION=${CONTAINERD_VERSION}-${IMAGE_BUILD_VERSION} \
    --build-arg REPO=${REPO} \
    --build-arg CACHEBUST="$(date +%s%N)" \
    --tag ${REPO}/${PROG}-test:${DOCKERIZED_VERSION} \
    --tag ${REPO}/${PROG}-test:${DOCKERIZED_VERSION}-${GOARCH} \
    --target test \
.
