#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

mkdir -p dist/{artifacts,bundle}

./scripts/package-binary
if [ "${ARCH}" = "amd64" ]; then ./scripts/package-windows-binary; fi
./scripts/package-bundle
if [ "${ARCH}" = "amd64" ]; then ./scripts/package-windows-bundle; fi
