#!/usr/bin/env bash
set -ex

cd $(dirname $0)/..

source ./scripts/version.sh

mkdir -p dist/{artifacts,bundle}

./scripts/package-binary
[ "${GOARCH}" != "arm64" ] && ./scripts/package-windows-binary
./scripts/package-bundle
[ "${GOARCH}" != "arm64" ] && ./scripts/package-windows-bundle
